### ISSUE TITLE
Error message in the server console in minecraft 1.18.2

### ISSUE THREAD

**Issue by pelusoide** [SuperRonanCraft/Pueblos#2]
I recently install the plugin and in appearance this plugin works well in minecraft 1.18.2, but when a user interacts in a claim where don't have permissions the server console returns this error.

> [11:33:56 ERROR]: Could not pass event PlayerInteractEvent to Pueblos v2.0.3
java.lang.NullPointerException: Cannot invoke "me.RonanCraft.Pueblos.resources.claims.enums.CLAIM_FLAG.getDefault()" because "flag" is null
        at me.RonanCraft.Pueblos.resources.claims.ClaimFlags.getFlag(ClaimFlags.java:27) ~[Pueblos-2.0.3.jar:?]
        at me.RonanCraft.Pueblos.resources.claims.ClaimHandler.allowInteract(ClaimHandler.java:278) ~[Pueblos-2.0.3.jar:?]
        at me.RonanCraft.Pueblos.player.events.PueblosEvents.allowInteract(PueblosEvents.java:37) ~[Pueblos-2.0.3.jar:?]
        at me.RonanCraft.Pueblos.player.events.EventInteract.onInteract(EventInteract.java:52) ~[Pueblos-2.0.3.jar:?]
        at me.RonanCraft.Pueblos.player.events.EventListener.onInteract(EventListener.java:62) ~[Pueblos-2.0.3.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-261]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[paper-1.18.2.jar:git-Paper-261]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:507) ~[paper-1.18.2.jar:git-Paper-261]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502) ~[paper-1.18.2.jar:git-Paper-261]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:229) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1769) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-261]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-261]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-261]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-261]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-261]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1503) ~[paper-1.18.2.jar:git-Paper-261]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-261]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-261]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

I am using paper and the version is paper-1.18.2-261.

**Comment by strawmelonjuice** [comment]
On 1.19.2 still!

**Comment by SuperRonanCraft** [comment]
> On 1.19.2 still!

> I recently install the plugin and in appearance this plugin works well in minecraft 1.18.2, but when a user interacts in a claim where don't have permissions the server console returns this error.

Oh yeah, this was fixed a long time ago in 2.1.0, please update mates
